### ISSUE TITLE
[Jupyterhub] Attempting to access private S3 buckets returns sts:AssumeRoleWithWebIdentity permission error

### ISSUE THREAD

**Issue by elyall** [awslabs/data-on-eks#346]
## Description

After deploying the `Jupyterhub` blueprint with `jupyter_hub_auth_mechanism = "dummy"`, trying to access private S3 buckets results in the error:
```python
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 1.0.2

- Terraform version: 1.5.7

- Provider version(s): 
  - provider registry.terraform.io/hashicorp/aws v5.20.1
  - provider registry.terraform.io/hashicorp/cloudinit v2.3.2
  - provider registry.terraform.io/hashicorp/helm v2.11.0
  - provider registry.terraform.io/hashicorp/kubernetes v2.23.0
  - provider registry.terraform.io/hashicorp/random v3.1.0
  - provider registry.terraform.io/hashicorp/time v0.9.1
  - provider registry.terraform.io/hashicorp/tls v4.0.4

## Reproduction Code [Required]

Repo with code [here](https://github.com/elyall/data-on-eks/tree/main/ai-ml/jupyterhub). 

<details>
<summary>Here's the main code that was added:</summary>

```terraform
# ------------------------------------------------------------------------------
# Private S3 bucket
# ------------------------------------------------------------------------------

resource "random_string" "example" {
  length  = 8
  special = false
  lower   = true
  upper   = false
}

resource "aws_s3_bucket" "example" {
  bucket = "test-bucket-${random_string.example.result}"

  tags = {
    Name        = "My bucket"
    Environment = "Dev"
  }
}

resource "aws_s3_bucket_ownership_controls" "example" {
  bucket = aws_s3_bucket.example.id
  rule {
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_acl" "example" {
  depends_on = [aws_s3_bucket_ownership_controls.example]

  bucket = aws_s3_bucket.example.id
  acl    = "private"
}

# ------------------------------------------------------------------------------
# Add encryption
# ------------------------------------------------------------------------------

# Enable server-side encryption by default
resource "aws_kms_key" "s3_encryption" {
  description             = "This key is used to encrypt bucket objects"
  deletion_window_in_days = 10
}

resource "aws_s3_bucket_server_side_encryption_configuration" "example" {
  bucket = aws_s3_bucket.example.bucket

  rule {
    apply_server_side_encryption_by_default {
      kms_master_key_id = aws_kms_key.s3_encryption.arn
      sse_algorithm     = "aws:kms"
    }
  }
}

# ------------------------------------------------------------------------------
# Access policies
# ------------------------------------------------------------------------------

resource "aws_iam_policy" "example_get" {
  name        = "${aws_s3_bucket.example.bucket}-get"
  path        = "/"
  description = "Policy to allow users to get objects in s3 bucket ${aws_s3_bucket.example.bucket}"

  policy = <<-EOT
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Download",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketVersions",
                "s3:GetObject",
                "s3:GetObjectVersion"
            ],
            "Resource": [
                "${aws_s3_bucket.example.arn}",
                "${aws_s3_bucket.example.arn}/*"
            ]
        },
        {
            "Sid": "Decrypt",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt"
            ],
            "Resource": [
                "${aws_kms_key.s3_encryption.arn}"
            ]
        }
    ]
}
EOT
}

resource "aws_iam_policy" "example_put" {
  name        = "${aws_s3_bucket.example.bucket}-put"
  path        = "/"
  description = "Policy to allow users to put objects in s3 bucket ${aws_s3_bucket.example.bucket}"

  policy = <<-EOT
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Upload",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "${aws_s3_bucket.example.arn}",
                "${aws_s3_bucket.example.arn}/*"
            ]
        },
        {
            "Sid": "Encrypt",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Encrypt",
                "kms:GenerateDataKey*"
            ],
            "Resource": [
                "${aws_kms_key.s3_encryption.arn}"
            ]
        }
    ]
}
EOT
}

# ------------------------------------------------------------------------------
# Test object
# ------------------------------------------------------------------------------

resource "aws_iam_user_policy_attachment" "example" {
  user       = var.local_aws_user
  policy_arn = aws_iam_policy.example_put.arn # each.value
}

resource "aws_s3_object" "example" {
  key        = "test_folder/test_object.txt"
  bucket     = aws_s3_bucket.example.id
  content    = "Test object text"
  kms_key_id = aws_kms_key.s3_encryption.arn
}

# ------------------------------------------------------------------------------
# Delete KMS key
# ------------------------------------------------------------------------------

resource "aws_iam_policy" "kms_key" {
  name        = "delete_kms_key"
  path        = "/"
  description = "Policy to allow users to delete ${aws_kms_key.s3_encryption.arn}"

  policy = <<-EOT
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DeleteKMS",
            "Effect": "Allow",
            "Action": [
                "kms:ScheduleKeyDeletion"
            ],
            "Resource": [
                "${aws_kms_key.s3_encryption.arn}"
            ]
        }
    ]
}
EOT
}

resource "aws_iam_user_policy_attachment" "kms_key" {
  user       = var.local_aws_user
  policy_arn = aws_iam_policy.kms_key.arn # each.value
}
```
</details>

1. pull [the reproduction repo](https://github.com/elyall/data-on-eks) or [start from scratch](https://github.com/awslabs/data-on-eks) and add the code above to the blueprint to deploy a private bucket, access policies, and test object
    - if starting from scratch add `aws_iam_policy.example_get.arn` to `jupyterhub_single_user_irsa` [here](https://github.com/awslabs/data-on-eks/blob/873e1ce1e0b58e84335cb6187aa3e2631089e9d9/ai-ml/jupyterhub/jupyterhub.tf#L16) so it reads:
```terraform
  role_policy_arns = {
    policy = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
    test_policy = aws_iam_policy.example_get.arn
  }
```

2. define the variable `local_aws_user` so that `aws_s3_object.example` can be pushed to the bucket (or comment out the "Test object" section to leave the bucket empty) and so the KMS key can be deleted. 
3. `cd data-on-eks/ai-ml/jupyterhub/` and run `./install.sh`
4. run `kubectl port-forward service/proxy-public 8001:80 -n jupyterhub`
5. navigate to http://127.0.0.1:8001/, log into the hub with any name and password, then open a terminal on the hub
6. install boto3 via `$ conda install boto3`
7. then copy the bucket name and try to access it via `$ python`
```python
>>> import boto3
>>> s3 = boto.client('s3')
>>> s3.list_objects_v2(Bucket=bucket_name)
```

## Expected behavior

I'd expect granting `jupyterhub_single_user_irsa` the proper access policies would allow it to access the private bucket. Running `s3.list_objects_v2(Bucket=bucket_name)` should return something including naming the test object `test_folder/test_object.txt`.

## Actual behavior

```python
>>> import boto3
>>> s3 = boto.client('s3')
>>> s3.list_objects_v2(Bucket="test-bucket-rzccplrn")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/client.py", line 963, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/client.py", line 986, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/opt/conda/lib/python3.11/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/signers.py", line 180, in sign
    auth = self.get_auth_instance(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/signers.py", line 284, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/credentials.py", line 611, in get_frozen_credentials
    self._refresh()
  File "/opt/conda/lib/python3.11/site-packages/botocore/credentials.py", line 499, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/opt/conda/lib/python3.11/site-packages/botocore/credentials.py", line 515, in _protected_refresh
    metadata = self._refresh_using()
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/credentials.py", line 662, in fetch_credentials
    return self._get_cached_credentials()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/credentials.py", line 672, in _get_cached_credentials
    response = self._get_credentials()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/credentials.py", line 906, in _get_credentials
    return client.assume_role_with_web_identity(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the AssumeRoleWithWebIdentity operation: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

## Additional context

I am also running into this error after deploying the `ray` blueprint. More context [here](https://github.com/awslabs/data-on-eks/issues/338).

**Comment by elyall** [comment]
Is it possible that the role needs to be explicitly assumed by `boto3` within the python processes running within the jupyter session or `ray.remote` call and not just passed in automatically?

**Comment by elyall** [comment]
For now my workaround is to create a user with the proper policies attached, and then to inject the user's credentials as environment variables that `boto3` automatically pickups. One note, this results in all sessions/jobs having the same credentials.

Terraform code:
```terraform
# ------------------------------------------------------------------------------
# Create user
# ------------------------------------------------------------------------------

resource "aws_iam_user" "single_user" {
  name = "single_user"
}

resource "aws_iam_access_key" "single_user" {
  user = aws_iam_user.single_user.name
}

resource "aws_iam_user_policy_attachment" "example_get" {
  user       = aws_iam_user.single_user.name
  policy_arn = aws_iam_policy.example_get.arn
}

#-----------------------------------------------------------------------------------------
# Add user credentials as K8S secrets in relevant namespaces
#-----------------------------------------------------------------------------------------

resource "kubernetes_secret" "jupyter_user" {
  metadata {
    name      = "jupyter-user"
    namespace = kubernetes_namespace.jupyterhub.metadata[0].name
  }
  data = {
    AWS_ACCESS_KEY_ID     = aws_iam_access_key.single_user.id
    AWS_SECRET_ACCESS_KEY = aws_iam_access_key.single_user.secret
    AWS_DEFAULT_REGION    = local.region
  }
  type = "Opaque"
}

resource "kubernetes_secret" "ray_user" {
  metadata {
    name      = "ray-user"
    namespace = kubernetes_namespace.ray.metadata[0].name
  }
  data = {
    AWS_ACCESS_KEY_ID     = aws_iam_access_key.jupyter_user.id
    AWS_SECRET_ACCESS_KEY = aws_iam_access_key.jupyter_user.secret
    AWS_DEFAULT_REGION    = local.region
  }
  type = "Opaque"
}
```

Relevant jupyterhub helm chart config:
```yaml
singleuser:
  extraEnv:
    AWS_ACCESS_KEY_ID:
      valueFrom:
        secretKeyRef:
          name: jupyter-user
          key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: jupyter-user
          key: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:
      valueFrom:
        secretKeyRef:
          name: jupyter-user
          key: AWS_DEFAULT_REGION
```

Relevant ray-cluster helm chart config:
```yaml
head:
  envFrom:
    - secretRef:
        name: ray-user
worker:
  envFrom:
    - secretRef:
        name: ray-user
```

**Comment by elyall** [comment]
See https://github.com/awslabs/data-on-eks/issues/347 which schematizes a work around.
